// Auto-generated real seed data from rekap_stok_gudang_sppg.xlsx
import { NonFoodExpense, WasteLog, ItemMaster, MenuOrder, SchoolBeneficiaryAllocation, Employee, EmployeeAttendance } from '../types/warehouse';

export const REAL_NONFOOD_EXPENSES: NonFoodExpense[] = [
  {
    "id": "PRL-EXP-001",
    "date": "20 sept 2026",
    "itemName": "kresek merah",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "19.55",
    "volunteer": "roni",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "roni",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 19.55 oleh roni",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-002",
    "date": "20 sept 2026",
    "itemName": "trashbag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "20.30",
    "volunteer": "puspitasari",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "puspitasari",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.30 oleh puspitasari",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-003",
    "date": "20 sept 2026",
    "itemName": "obat mylanta",
    "quantity": "1 kaplet",
    "unit": "Pack",
    "time": "21.37",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 21.37 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-004",
    "date": "20 sept 2026",
    "itemName": "handsaplast",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "23.00",
    "volunteer": "nafis",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nafis",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.00 oleh nafis",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-005",
    "date": "20 sept 2026",
    "itemName": "handsaplast",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "23.17",
    "volunteer": "usli",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "usli",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.17 oleh usli",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-006",
    "date": "20 sept 2026",
    "itemName": "tissue",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "23.17",
    "volunteer": "b sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "b sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.17 oleh b sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-007",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 bendel",
    "unit": "Pack",
    "time": "23.17",
    "volunteer": "b sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "b sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.17 oleh b sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-008",
    "date": "21 sept 2026",
    "itemName": "trash bag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "01.36",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 01.36 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-009",
    "date": "21 sept 2026",
    "itemName": "masker 1 pack hijab",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "03.03",
    "volunteer": "lutvya",
    "pic": "riski",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutvya",
    "recordedBy": "riski",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.03 oleh lutvya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-010",
    "date": "21 sept 2026",
    "itemName": "plastik buah",
    "quantity": "7 pack",
    "unit": "Pack",
    "time": "03.03",
    "volunteer": "lutvya",
    "pic": "riski",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutvya",
    "recordedBy": "riski",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.03 oleh lutvya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-011",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "03.03",
    "volunteer": "lutvya",
    "pic": "riski",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutvya",
    "recordedBy": "riski",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.03 oleh lutvya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-012",
    "date": "21 sept 2026",
    "itemName": "trashbag 60x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "03.21",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.21 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-013",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "05.57",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 05.57 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-014",
    "date": "21 sept 2026",
    "itemName": "kresek merah",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "08.19",
    "volunteer": "nabila",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 08.19 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-015",
    "date": "21 sept 2026",
    "itemName": "rinso softergent",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "10.02",
    "volunteer": "nabila",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 10.02 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-016",
    "date": "21 sept 2026",
    "itemName": "trashbag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "12.18",
    "volunteer": "dudin",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "dudin",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 12.18 oleh dudin",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-017",
    "date": "21 sept 2026",
    "itemName": "sunlight",
    "quantity": "1 jurigen",
    "unit": "Pack",
    "time": "12.20",
    "volunteer": "zenli",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "zenli",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 12.20 oleh zenli",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-018",
    "date": "21 sept 2026",
    "itemName": "wipol oxyklin",
    "quantity": "1 jurigen",
    "unit": "Pack",
    "time": "13.40",
    "volunteer": "nabila",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 13.40 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-019",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "18.15",
    "volunteer": "anggita",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "anggita",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 18.15 oleh anggita",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-020",
    "date": "21 sept 2026",
    "itemName": "sarung tangan plastik",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "18.15",
    "volunteer": "angita",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "angita",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 18.15 oleh angita",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-021",
    "date": "21 sept 2026",
    "itemName": "tissue",
    "quantity": "1pack",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "nafis",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nafis",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh nafis",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-022",
    "date": "21 sept 2026",
    "itemName": "salonpas koyo",
    "quantity": "1 biji",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-023",
    "date": "21 sept 2026",
    "itemName": "minyak kayu putih",
    "quantity": "1 botol",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "bu nur",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu nur",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh bu nur",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-024",
    "date": "21 sept 2026",
    "itemName": "handsaplast koyo",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-025",
    "date": "22 sept 2026",
    "itemName": "trashbag 60x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "00.29",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 00.29 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-026",
    "date": "22 sept 2026",
    "itemName": "handsaplast",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "04.38",
    "volunteer": "lutfiya",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutfiya",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 04.38 oleh lutfiya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-027",
    "date": "22 sept 2026",
    "itemName": "soklin softergent kecil",
    "quantity": "1 pcs",
    "unit": "Pack",
    "time": "08.23",
    "volunteer": "andri",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "andri",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 08.23 oleh andri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-028",
    "date": "22 sept 2026",
    "itemName": "sarung tangan karet biru",
    "quantity": "1 pcs",
    "unit": "Pack",
    "time": "09.24",
    "volunteer": "nabila",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 09.24 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-029",
    "date": "22 sept 2026",
    "itemName": "trash bag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "12.20",
    "volunteer": "mansur",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "mansur",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 12.20 oleh mansur",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-030",
    "date": "22 sept 2026",
    "itemName": "sunlight jurigen 5l",
    "quantity": "1 pcs",
    "unit": "Pack",
    "time": "13.48",
    "volunteer": "dudin",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "dudin",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 13.48 oleh dudin",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-031",
    "date": "22 sept 2026",
    "itemName": "sarung tangan karet biru",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "19.43",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 19.43 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-032",
    "date": "22 sept 2026",
    "itemName": "trash bag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "20.00",
    "volunteer": "saipul",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saipul",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.00 oleh saipul",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-033",
    "date": "22 sept 2026",
    "itemName": "tissue dapur besar",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "19.43",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 19.43 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  }
];

export const REAL_WASTE_LOGS: WasteLog[] = [
  {
    "id": "WST-001",
    "day": "jumat",
    "date": "2026-09-18",
    "wasteCategory": "karbohidrat",
    "itemName": "Limbah karbohidrat",
    "quantity": 64.16,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-002",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "sayur",
    "itemName": "Limbah sayur",
    "quantity": 48.12,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-003",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "protein hewani",
    "itemName": "Limbah protein hewani",
    "quantity": 16.4,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-004",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "protein nabati",
    "itemName": "Limbah protein nabati",
    "quantity": 24.6,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-005",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "buah",
    "itemName": "Limbah buah",
    "quantity": 8.02,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-006",
    "day": "senin",
    "date": "2026-09-21",
    "wasteCategory": "karbohidrat",
    "itemName": "Limbah karbohidrat",
    "quantity": 62.92,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-007",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "sayur",
    "itemName": "Limbah sayur",
    "quantity": 47.19,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-008",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "protein hewani",
    "itemName": "Limbah protein hewani",
    "quantity": 15.73,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-009",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "protein nabati",
    "itemName": "Limbah protein nabati",
    "quantity": 23.6,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-010",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "buah",
    "itemName": "Limbah buah",
    "quantity": 7.86,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-011",
    "day": "selasa",
    "date": "2026-09-22",
    "wasteCategory": "karbohidrat",
    "itemName": "Limbah karbohidrat",
    "quantity": 59.48,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-22T00:00:00Z"
  },
  {
    "id": "WST-012",
    "day": "selasa",
    "date": "2026-09-22",
    "wasteCategory": "sayur",
    "itemName": "Limbah sayur",
    "quantity": 44.61,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-22T00:00:00Z"
  },
  {
    "id": "WST-013",
    "day": "selasa",
    "date": "2026-09-22",
    "wasteCategory": "protein hewani",
    "itemName": "Limbah protein hewani",
    "quantity": 14.87,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-22T00:00:00Z"
  },
  {
    "id": "WST-014",
    "day": "selasa",
    "date": "2026-09-22",
    "wasteCategory": "protein nabati",
    "itemName": "Limbah protein nabati",
    "quantity": 29.74,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-22T00:00:00Z"
  },
  {
    "id": "WST-015",
    "day": "selasa",
    "date": "2026-09-22",
    "wasteCategory": "buah",
    "itemName": "Limbah buah",
    "quantity": 0,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-22T00:00:00Z"
  },
  {
    "id": "WST-016",
    "day": "rabu",
    "date": "2026-09-23",
    "wasteCategory": "karbohidrat",
    "itemName": "Limbah karbohidrat",
    "quantity": 69.36,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-23T00:00:00Z"
  },
  {
    "id": "WST-017",
    "day": "rabu",
    "date": "2026-09-23",
    "wasteCategory": "sayur",
    "itemName": "Limbah sayur",
    "quantity": 52.02,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-23T00:00:00Z"
  },
  {
    "id": "WST-018",
    "day": "rabu",
    "date": "2026-09-23",
    "wasteCategory": "protein hewani",
    "itemName": "Limbah protein hewani",
    "quantity": 17.34,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-23T00:00:00Z"
  },
  {
    "id": "WST-019",
    "day": "rabu",
    "date": "2026-09-23",
    "wasteCategory": "protein nabati",
    "itemName": "Limbah protein nabati",
    "quantity": 26.01,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-23T00:00:00Z"
  },
  {
    "id": "WST-020",
    "day": "rabu",
    "date": "2026-09-23",
    "wasteCategory": "buah",
    "itemName": "Limbah buah",
    "quantity": 8.67,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-23T00:00:00Z"
  },
  {
    "id": "WST-021",
    "day": "kamis",
    "date": "2026-09-24",
    "wasteCategory": "karbohidrat",
    "itemName": "Limbah karbohidrat",
    "quantity": 55.72,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-24T00:00:00Z"
  },
  {
    "id": "WST-022",
    "day": "kamis",
    "date": "2026-09-24",
    "wasteCategory": "sayur",
    "itemName": "Limbah sayur",
    "quantity": 41.79,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-24T00:00:00Z"
  },
  {
    "id": "WST-023",
    "day": "kamis",
    "date": "2026-09-24",
    "wasteCategory": "protein hewani",
    "itemName": "Limbah protein hewani",
    "quantity": 13.93,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-24T00:00:00Z"
  },
  {
    "id": "WST-024",
    "day": "kamis",
    "date": "2026-09-24",
    "wasteCategory": "protein nabati",
    "itemName": "Limbah protein nabati",
    "quantity": 20.89,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-24T00:00:00Z"
  },
  {
    "id": "WST-025",
    "day": "kamis",
    "date": "2026-09-24",
    "wasteCategory": "buah",
    "itemName": "Limbah buah",
    "quantity": 6.96,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-24T00:00:00Z"
  }
];

export const REAL_EQUIPMENT_ITEMS: ItemMaster[] = [
  {
    "id": "PRL-001",
    "name": "natura desinfectant food grade 5l",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 2,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "tanggal so gudang per 21 september 2026",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-002",
    "name": "sunlight cairan pencuci piring 5l",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 4,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-003",
    "name": "oixs cleaner 1l",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-004",
    "name": "be clean tissue serbaguna",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 3,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-005",
    "name": "spons cuci hijau",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 10,
    "reorderPoint": 20,
    "currentStock": 37,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-006",
    "name": "sabut cuci stainless",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 22,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-007",
    "name": "plastik kresek besar merah 50pc",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 8,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-008",
    "name": "lap besar",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 4,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-009",
    "name": "lap microfiber",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 67,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-010",
    "name": "lap kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 7,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-011",
    "name": "kanebo kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 6,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-012",
    "name": "plastik 1/4kg joyoboyo 100 lembar",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 28,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-013",
    "name": "sarung tangan plastik kaka 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 21,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-014",
    "name": "optima trashbag 80x100",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 7,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-015",
    "name": "optima trashbag 60x100",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-016",
    "name": "rajawali trashbag 30x40",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 1.5,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-017",
    "name": "onemed masker biru 3 play 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 6,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-018",
    "name": "onemed masker biru 3 play hijab 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-019",
    "name": "neo health masker biru 3 play 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 9,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-020",
    "name": "baymed masker hijau 3 play hijau 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 2,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-021",
    "name": "altamed nurse cap penutup kepala 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 5,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-022",
    "name": "sabun cuci tangan",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-023",
    "name": "gayung kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-024",
    "name": "cikrak kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-025",
    "name": "petromax plastik kecil 12x24 100 lembar",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-026",
    "name": "lancar kresek kecil bening",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 2.5,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-027",
    "name": "kresek klin warna warni kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 2,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-028",
    "name": "ctik plastik 7x10 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 81,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-029",
    "name": "ctik plastik 6x10 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 13,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-030",
    "name": "klip plastik 25x16 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-031",
    "name": "tempat saus 20 ml",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 20,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-032",
    "name": "plastik packaging ag box uk sedang",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 100,
    "reorderPoint": 200,
    "currentStock": 2000,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG Jeru Tumpang",
    "lastMovementDate": "2026-09-21"
  }
];

export const DEFAULT_SCHOOL_BENEFICIARIES: SchoolBeneficiaryAllocation[] = [
  {
    id: 'SCH-001',
    schoolName: 'SDN 1 Jeru',
    category: 'SD / MI',
    portionCount: 380,
    deliveryTime: '09.45 WIB',
    contactPerson: 'Pak Hadi (Kepala Sekolah)',
    phone: '0812-3344-5501',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 1 - Area Jeru Timur',
  },
  {
    id: 'SCH-002',
    schoolName: 'SDN 2 Jeru',
    category: 'SD / MI',
    portionCount: 245,
    deliveryTime: '10.00 WIB',
    contactPerson: 'Bu Nurul (Koordinator Gizi)',
    phone: '0813-2211-7702',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 1 - Area Jeru Barat',
  },
  {
    id: 'SCH-003',
    schoolName: 'SDN 1 Tumpang',
    category: 'SD / MI',
    portionCount: 420,
    deliveryTime: '09.30 WIB',
    contactPerson: 'Pak Sugeng (Kesiswaan)',
    phone: '0812-4455-8803',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 2 - Pusat Tumpang',
  },
  {
    id: 'SCH-004',
    schoolName: 'SDN 2 Tumpang',
    category: 'SD / MI',
    portionCount: 310,
    deliveryTime: '09.50 WIB',
    contactPerson: 'Ibu Sri Rahayu (Guru PJOK)',
    phone: '0857-9988-1104',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 2 - Tumpang Krajan',
  },
  {
    id: 'SCH-005',
    schoolName: 'SDN 3 Malangsuko',
    category: 'SD / MI',
    portionCount: 250,
    deliveryTime: '10.15 WIB',
    contactPerson: 'Pak Bambang (Humas)',
    phone: '0813-7766-3305',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 3 - Malangsuko Utara',
  },
  {
    id: 'SCH-006',
    schoolName: 'MI Miftahul Huda Jeru',
    category: 'SD / MI',
    portionCount: 265,
    deliveryTime: '10.10 WIB',
    contactPerson: 'Ustadz Fauzi (Kepala Madrasah)',
    phone: '0812-9900-4406',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 1 - Komplek Pesantren',
  },
  {
    id: 'SCH-007',
    schoolName: 'SMPN 1 Tumpang',
    category: 'SMP / MTs',
    portionCount: 430,
    deliveryTime: '10.30 WIB',
    contactPerson: 'Pak Agus Wibowo (Waka Sarpras)',
    phone: '0821-6677-8807',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 2 - Jenjang Menengah',
  },
  {
    id: 'SCH-008',
    schoolName: 'SMPN 2 Tumpang',
    category: 'SMP / MTs',
    portionCount: 220,
    deliveryTime: '10.45 WIB',
    contactPerson: 'Bu Endang (UKS)',
    phone: '0813-8899-2208',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 3 - Selatan Pasar',
  },
  {
    id: 'SCH-009',
    schoolName: 'MTs Negeri 2 Malang (Tumpang)',
    category: 'SMP / MTs',
    portionCount: 180,
    deliveryTime: '10.40 WIB',
    contactPerson: 'Pak Munir (Staf Kesiswaan)',
    phone: '0856-1122-3309',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi 2 - Depan Lapangan',
  },
  {
    id: 'SCH-010',
    schoolName: 'TK Pertiwi Jeru',
    category: 'PAUD / TK',
    portionCount: 110,
    deliveryTime: '09.00 WIB',
    contactPerson: 'Bu Retno (Kepala TK)',
    phone: '0812-7788-9910',
    status: 'TERKIRIM',
    notes: 'Jalur Distribusi Khusus Pagi / Snack',
  },
  {
    id: 'SCH-011',
    schoolName: 'TK Dharma Wanita 1 Tumpang',
    category: 'PAUD / TK',
    portionCount: 95,
    deliveryTime: '09.15 WIB',
    contactPerson: 'Bu Yuni (Wali Kelas A)',
    phone: '0813-4455-6611',
    status: 'TERKIRIM',
    notes: 'Porsi balita halus rendah garam',
  },
  {
    id: 'SCH-012',
    schoolName: 'PAUD Melati Jeru',
    category: 'PAUD / TK',
    portionCount: 115,
    deliveryTime: '09.10 WIB',
    contactPerson: 'Ibu Titik (Pengelola)',
    phone: '0857-3344-5512',
    status: 'TERKIRIM',
    notes: 'Prioritas pengantaran awal pagi',
  },
  {
    id: 'SCH-013',
    schoolName: 'Posyandu Mawar Jeru (Sasaran B3)',
    category: 'Ibu Hamil & Balita (B3)',
    portionCount: 64,
    deliveryTime: '08.45 WIB',
    contactPerson: 'Bidan Desa Siti Khotimah',
    phone: '0812-8877-6613',
    status: 'TERKIRIM',
    notes: 'Gizi spesifik B3 (Balita Bawah Tiga Tahun & Bumil)',
  },
  {
    id: 'SCH-014',
    schoolName: 'Posyandu Melati Tumpang (Sasaran B3)',
    category: 'Ibu Hamil & Balita (B3)',
    portionCount: 60,
    deliveryTime: '08.45 WIB',
    contactPerson: 'Ibu Rina (Kader Posyandu Utama)',
    phone: '0813-5566-7714',
    status: 'TERKIRIM',
    notes: 'Gizi tinggi protein telur, sayur rebus & susu',
  },
];

export const REAL_MENU_ORDERS: MenuOrder[] = [
  {
    id: 'ORD-2026-001',
    date: '2026-09-20',
    poDate: 'Minggu, 19 Sept 2026',
    mealSession: 'Siang',
    menuTitle: 'Nasi Putih, Ayam Krispi Sambal & Selada, Tahu Cabe Garam, Steam Buncis Wortel',
    menuDescription: 'Menu lengkap pemenuhan gizi terpadu SPPG Jeru Tumpang. Daging ayam segar krispi berbalur saus rempah nusantara dengan protein tahu cabe garam dan serat sayuran segar.',
    specialDietB3: 'Menu B3 (Balita & Bumil): Ayam Krispi Fillet Suwir Lembut, Orak-Arik Telur, Tahu Kecap Manis Rendah Garam, Buah Melon Manis',
    targetPortions: 3044,
    totalBeneficiaries: 3044,
    status: 'DISTRIBUTED',
    chefInCharge: 'Chef Joko Santoso & Tim Dapur SPPG Jeru Tumpang',
    notes: 'Seluruh 3.044 porsi selesai dimasak dan disalurkan tepat waktu ke 14 sekolah & posyandu sasaran. Diterima oleh PIC Akmal.',
    createdAt: '2026-09-19T14:00:00Z',
    beneficiaryAllocations: DEFAULT_SCHOOL_BENEFICIARIES,
    keyIngredients: [
      { itemName: 'Beras Mentari 25kg', category: 'Bahan Kering', quantity: 7, unit: 'Sak (175 Kg)', unitPrice: 362500, totalCost: 2537500 },
      { itemName: 'Ayam Potong Segar', category: 'Bahan Basah', quantity: 264, unit: 'Kg', unitPrice: 38000, totalCost: 10032000 },
      { itemName: 'Tahu Putih Segar', category: 'Bahan Basah', quantity: 520, unit: 'Pcs', unitPrice: 2500, totalCost: 1300000 },
      { itemName: 'Minyak Goreng Tropical 2L', category: 'Bahan Kering', quantity: 9, unit: 'Dus (108 L)', unitPrice: 216000, totalCost: 1944000 },
      { itemName: 'Buncis Segar Hijau', category: 'Bahan Basah', quantity: 65, unit: 'Kg', unitPrice: 12000, totalCost: 780000 },
      { itemName: 'Wortel Segar Super', category: 'Bahan Basah', quantity: 65, unit: 'Kg', unitPrice: 12000, totalCost: 780000 },
      { itemName: 'Buah Melon Manis', category: 'Bahan Basah', quantity: 207, unit: 'Kg', unitPrice: 10000, totalCost: 2070000 },
      { itemName: 'Bumbu Dapur, Cabai & Bawang', category: 'Bahan Basah', quantity: 38, unit: 'Kg', unitPrice: 28000, totalCost: 1064000 },
      { itemName: 'Tepung Terigu Segitiga Biru', category: 'Bahan Kering', quantity: 3, unit: 'Sak', unitPrice: 220000, totalCost: 660000 },
    ],
    poArrivalItems: [
      { category: 'Protein', itemName: 'Ayam Potong', qtyOrder: '264 kg', qtyArrived: '264 kg', supplier: 'Ayam Segar Fajar', arrivalTime: '09.00', pic: 'Akmal', unitPrice: 38000, totalCost: 10032000 },
      { category: 'Protein', itemName: 'Tahu Putih', qtyOrder: '520 pcs', qtyArrived: '520 pcs', supplier: 'Tahu Rio', arrivalTime: '09.30', pic: 'Akmal', unitPrice: 2500, totalCost: 1300000 },
      { category: 'Sembako', itemName: 'Gula 1 kg', qtyOrder: '10 pcs', qtyArrived: '10 kg', supplier: 'Tumpang Grosir', arrivalTime: '14.53', pic: 'Akmal', unitPrice: 17500, totalCost: 175000 },
      { category: 'Sembako', itemName: 'Royco Kaldu', qtyOrder: '2 dus', qtyArrived: '2 dus', supplier: 'Tumpang Grosir', arrivalTime: '14.53', pic: 'Akmal', unitPrice: 240000, totalCost: 480000 },
      { category: 'Sembako', itemName: 'Soda Kue', qtyOrder: '1 kg', qtyArrived: '1 kg', supplier: 'Tumpang Grosir', arrivalTime: '14.53', pic: 'Akmal', unitPrice: 25000, totalCost: 25000 },
      { category: 'Sembako', itemName: 'Tepung Terigu Segitiga', qtyOrder: '3 sak', qtyArrived: '3 sak', supplier: 'Tumpang Grosir', arrivalTime: '14.53', pic: 'Akmal', unitPrice: 220000, totalCost: 660000 },
      { category: 'Sembako', itemName: 'Minyak Tropical 2L', qtyOrder: '9 dus', qtyArrived: '9 dus', supplier: 'Tumpang Grosir', arrivalTime: '14.53', pic: 'Akmal', unitPrice: 216000, totalCost: 1944000 },
      { category: 'Sembako', itemName: 'Beras Mentari 25kg', qtyOrder: '7 sak', qtyArrived: '7 sak', supplier: 'Tumpang Grosir', arrivalTime: '14.53', pic: 'Akmal', unitPrice: 362500, totalCost: 2537500 },
      { category: 'Sayur & Buah', itemName: 'Buncis Segar', qtyOrder: '65 kg', qtyArrived: '66 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 12000, totalCost: 792000 },
      { category: 'Sayur & Buah', itemName: 'Wortel Segar', qtyOrder: '65 kg', qtyArrived: '66 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 12000, totalCost: 792000 },
      { category: 'Sayur & Buah', itemName: 'Tomat Buah', qtyOrder: '25 kg', qtyArrived: '25 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 12000, totalCost: 300000 },
      { category: 'Sayur & Buah', itemName: 'Cabe Rawit', qtyOrder: '8 kg', qtyArrived: '8 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 35000, totalCost: 280000 },
      { category: 'Sayur & Buah', itemName: 'Bawang Putih', qtyOrder: '8 kg', qtyArrived: '8 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 36000, totalCost: 288000 },
      { category: 'Sayur & Buah', itemName: 'Bawang Merah', qtyOrder: '5 kg', qtyArrived: '5 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 34000, totalCost: 170000 },
      { category: 'Sayur & Buah', itemName: 'Buah Melon Segar', qtyOrder: '121 pcs', qtyArrived: '207 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 10000, totalCost: 2070000 },
      { category: 'Bumbu', itemName: 'Tambahan Terasi', qtyOrder: '8 kg', qtyArrived: '8 kg', supplier: 'Pak Beni', arrivalTime: '16.19', pic: 'Akmal', unitPrice: 40000, totalCost: 320000 },
    ],
  },
  {
    id: 'ORD-2026-002',
    date: '2026-09-21',
    poDate: 'Senin, 20 Sept 2026',
    mealSession: 'Siang',
    menuTitle: 'Nasi Putih, Telur Dadar Isi Mie & Bayam Balado, Tahu Sutra Goreng (2 pcs), Pakcoy Bawang Putih, Susu Frisian Flag 115ml',
    menuDescription: 'Menu tinggi kalsium dan protein lengkap: Telur dadar tebal padat serat bayam dan mie telur, dilengkapi tahu sutra goreng lembut, tumis pakcoy gurih, dan susu UHT siap minum.',
    specialDietB3: 'Menu B3 (Balita & Bumil): Telur Dadar Halus & Bayam Rebus Cincang, Tahu Sutra Kukus, Susu UHT 115ml, Anggur Manis Kupas',
    targetPortions: 2571,
    totalBeneficiaries: 2571,
    status: 'COMPLETED',
    chefInCharge: 'Chef Joko Santoso & Tim Dapur SPPG Jeru Tumpang',
    notes: 'Distribusi tepat sasaran untuk 2.571 anak sekolah dasar dan balita 3T.',
    createdAt: '2026-09-20T13:00:00Z',
    beneficiaryAllocations: DEFAULT_SCHOOL_BENEFICIARIES.map(s => ({
      ...s,
      portionCount: Math.round(s.portionCount * (2571 / 3044)),
    })),
    keyIngredients: [
      { itemName: 'Beras Mentari 25kg', category: 'Bahan Kering', quantity: 6, unit: 'Sak (150 Kg)', unitPrice: 362500, totalCost: 2175000 },
      { itemName: 'Telur Ayam Ras Segar', category: 'Bahan Basah', quantity: 15, unit: 'Krat (225 Kg)', unitPrice: 420000, totalCost: 6300000 },
      { itemName: 'Tahu Sutra', category: 'Bahan Basah', quantity: 470, unit: 'Bks', unitPrice: 5000, totalCost: 2350000 },
      { itemName: 'Susu UHT 115ml Frisian Flag', category: 'Bahan Basah', quantity: 2571, unit: 'Pcs', unitPrice: 3200, totalCost: 8227200 },
      { itemName: 'Mie Kuning Telur (15kg)', category: 'Bahan Kering', quantity: 9, unit: 'Pack', unitPrice: 180000, totalCost: 1620000 },
      { itemName: 'Sayur Pakcoy Segar', category: 'Bahan Basah', quantity: 220, unit: 'Kg', unitPrice: 8000, totalCost: 1760000 },
      { itemName: 'Sayur Bayam Hijau', category: 'Bahan Basah', quantity: 30, unit: 'Kg', unitPrice: 8500, totalCost: 255000 },
      { itemName: 'Buah Anggur Merah', category: 'Bahan Basah', quantity: 60, unit: 'Kg', unitPrice: 35000, totalCost: 2100000 },
      { itemName: 'Minyak & Saos Delmonte', category: 'Bahan Kering', quantity: 6, unit: 'Dus', unitPrice: 185000, totalCost: 1110000 },
    ],
    poArrivalItems: [
      { category: 'Protein', itemName: 'Telur Ayam', qtyOrder: '15 krat', qtyArrived: '15 krat (225 kg)', supplier: 'Ayam Segar Tumpang', arrivalTime: '08.30', pic: 'Akmal', unitPrice: 420000, totalCost: 6300000 },
      { category: 'Protein', itemName: 'Tahu Sutra', qtyOrder: '470 bks', qtyArrived: '470 bks', supplier: 'Tahu Rio', arrivalTime: '16.58', pic: 'Akmal', unitPrice: 5000, totalCost: 2350000 },
      { category: 'Sembako', itemName: 'Beras Mentari 25kg', qtyOrder: '6 sak', qtyArrived: '6 sak', supplier: 'Tumpang Grosir', arrivalTime: '15.07', pic: 'Akmal', unitPrice: 362500, totalCost: 2175000 },
      { category: 'Sembako', itemName: 'Mie Kuning (15kg)', qtyOrder: '9 pack', qtyArrived: '9 pack', supplier: 'Tumpang Grosir', arrivalTime: '15.07', pic: 'Akmal', unitPrice: 180000, totalCost: 1620000 },
      { category: 'Sembako', itemName: 'Gula Pasir 1kg', qtyOrder: '5 kg', qtyArrived: '5 kg', supplier: 'Tumpang Grosir', arrivalTime: '15.07', pic: 'Akmal', unitPrice: 17500, totalCost: 87500 },
      { category: 'Sembako', itemName: 'Saos Tomat Delmonte 1kg', qtyOrder: '4 dus', qtyArrived: '4 dus', supplier: 'Tumpang Grosir', arrivalTime: '15.07', pic: 'Akmal', unitPrice: 160000, totalCost: 640000 },
      { category: 'Sembako', itemName: 'Saos Sambal Delmonte 1kg', qtyOrder: '2 dus', qtyArrived: '2 dus', supplier: 'Tumpang Grosir', arrivalTime: '15.07', pic: 'Akmal', unitPrice: 175000, totalCost: 350000 },
      { category: 'Sayur & Buah', itemName: 'Pakcoy Segar', qtyOrder: '220 kg', qtyArrived: '230 kg', supplier: 'Mas Widi', arrivalTime: '16.32', pic: 'Akmal', unitPrice: 8000, totalCost: 1840000 },
      { category: 'Sayur & Buah', itemName: 'Bayam Hijau', qtyOrder: '30 kg', qtyArrived: '33 kg', supplier: 'Mas Widi', arrivalTime: '16.32', pic: 'Akmal', unitPrice: 8500, totalCost: 280500 },
      { category: 'Sayur & Buah', itemName: 'Buah Anggur Segar', qtyOrder: '2 krat', qtyArrived: '2 krat (60 kg)', supplier: 'Mas Widi', arrivalTime: '16.32', pic: 'Akmal', unitPrice: 35000, totalCost: 2100000 },
      { category: 'Minuman', itemName: 'Susu Plain 115ml Frisian Flag', qtyOrder: '3044 pc', qtyArrived: '3060 pc', supplier: 'Distributor Frisian Flag', arrivalTime: '11.20', pic: 'Akmal', unitPrice: 3200, totalCost: 9792000 },
      { category: 'Bumbu', itemName: 'Kacang Tanah', qtyOrder: '25 kg', qtyArrived: '25 kg', supplier: 'Tumpang Grosir', arrivalTime: '15.07', pic: 'Akmal', unitPrice: 28000, totalCost: 700000 },
    ],
  },
  {
    id: 'ORD-2026-003',
    date: '2026-09-22',
    poDate: 'Selasa, 21 Sept 2026',
    mealSession: 'Siang',
    menuTitle: 'Nasi Putih Pulen, Ayam Katsu Crispy Saus Kari Wortel & Kentang, Tahu Goreng, Buah Kelengkeng Manis',
    menuDescription: 'Menu favorit siswa kaya zat gizi: Dada ayam katsu renyah dengan baluran saus kari jepang lembut bertabur wortel dadu dan kentang, tahu goreng bumbu kuning, dan kelengkeng manis.',
    specialDietB3: 'Menu B3 (Balita & Bumil): Martabak Tahu Telur Mini, Sup Wortel Kentang Kaldu Gurih, Ayam Suwir Saus Manis, Kelengkeng Kupas',
    targetPortions: 3044,
    totalBeneficiaries: 3044,
    status: 'COOKING',
    chefInCharge: 'Chef Joko Santoso & Tim Dapur SPPG Jeru Tumpang',
    notes: 'Persiapan marinasi ayam katsu dan perebusan saus kari dimulai pukul 06.00 WIB.',
    createdAt: '2026-09-21T15:30:00Z',
    beneficiaryAllocations: DEFAULT_SCHOOL_BENEFICIARIES,
    keyIngredients: [
      { itemName: 'Beras Mentari 25kg', category: 'Bahan Kering', quantity: 7, unit: 'Sak (175 Kg)', unitPrice: 362500, totalCost: 2537500 },
      { itemName: 'Ayam Fillet Dada Tanpa Kulit', category: 'Bahan Basah', quantity: 150, unit: 'Kg', unitPrice: 45000, totalCost: 6750000 },
      { itemName: 'Tahu Putih Segar', category: 'Bahan Basah', quantity: 527, unit: 'Pcs', unitPrice: 2500, totalCost: 1317500 },
      { itemName: 'Wortel & Kentang Sayur', category: 'Bahan Basah', quantity: 100, unit: 'Kg', unitPrice: 14000, totalCost: 1400000 },
      { itemName: 'Buah Kelengkeng Manis', category: 'Bahan Basah', quantity: 146, unit: 'Kg (12 Krat)', unitPrice: 28000, totalCost: 4088000 },
      { itemName: 'Tepung Panir & Terigu', category: 'Bahan Kering', quantity: 2, unit: 'Sak', unitPrice: 230000, totalCost: 460000 },
      { itemName: 'Minyak Goreng Sawit', category: 'Bahan Kering', quantity: 6, unit: 'Karton (72 L)', unitPrice: 216000, totalCost: 1296000 },
      { itemName: 'Bumbu Kari Jepang & Rempah', category: 'Bahan Kering', quantity: 22, unit: 'Paket', unitPrice: 50000, totalCost: 1100000 },
    ],
    poArrivalItems: [
      { category: 'Protein', itemName: 'Ayam Fillet Dada Tanpa Kulit', qtyOrder: '145 kg', qtyArrived: '25 sak (150 kg)', supplier: 'Ayam Segar Tumpang', arrivalTime: '08.09', pic: 'Akmal', unitPrice: 45000, totalCost: 6750000 },
      { category: 'Protein', itemName: 'Tahu Putih', qtyOrder: '527 pcs', qtyArrived: '527 pcs', supplier: 'Tahu Rio', arrivalTime: '15.07', pic: 'Akmal', unitPrice: 2500, totalCost: 1317500 },
      { category: 'Protein', itemName: 'Telur Ayam', qtyOrder: '1 krat', qtyArrived: '1 krat (16 kg)', supplier: 'Ayam Segar Tulus Besar', arrivalTime: '12.35', pic: 'Akmal', unitPrice: 420000, totalCost: 420000 },
      { category: 'Sembako', itemName: 'Beras Mentari 25kg', qtyOrder: '7 sak', qtyArrived: '7 sak', supplier: 'Tumpang Grosir', arrivalTime: '15.44', pic: 'Akmal', unitPrice: 362500, totalCost: 2537500 },
      { category: 'Sembako', itemName: 'Tepung Panir', qtyOrder: '1 sak', qtyArrived: '1 sak (25 kg)', supplier: 'Tumpang Grosir', arrivalTime: '15.44', pic: 'Akmal', unitPrice: 280000, totalCost: 280000 },
      { category: 'Sembako', itemName: 'Minyak Goreng', qtyOrder: '6 ktn', qtyArrived: '6 ktn', supplier: 'Tumpang Grosir', arrivalTime: '15.44', pic: 'Akmal', unitPrice: 216000, totalCost: 1296000 },
      { category: 'Sayur & Buah', itemName: 'Wortel Segar', qtyOrder: '50 kg', qtyArrived: '50 kg', supplier: 'Mas Widi', arrivalTime: '16.05', pic: 'Akmal', unitPrice: 12000, totalCost: 600000 },
      { category: 'Sayur & Buah', itemName: 'Kentang Dieng', qtyOrder: '50 kg', qtyArrived: '50 kg', supplier: 'Mas Widi', arrivalTime: '16.05', pic: 'Akmal', unitPrice: 16000, totalCost: 800000 },
      { category: 'Sayur & Buah', itemName: 'Buah Kelengkeng', qtyOrder: '12 krat', qtyArrived: '12 krat (146 kg)', supplier: 'Mas Widi', arrivalTime: '16.05', pic: 'Akmal', unitPrice: 28000, totalCost: 4088000 },
      { category: 'Bumbu', itemName: 'Bumbu Kari BMM', qtyOrder: '2 bal', qtyArrived: '2 bal', supplier: 'Tumpang Grosir', arrivalTime: '15.44', pic: 'Akmal', unitPrice: 180000, totalCost: 360000 },
      { category: 'Bumbu', itemName: 'Bumbu Kari Jepang Sasa 40g', qtyOrder: '20 pack', qtyArrived: '20 pack', supplier: 'Tumpang Grosir', arrivalTime: '15.44', pic: 'Akmal', unitPrice: 35000, totalCost: 700000 },
      { category: 'Bahan Olahan', itemName: 'Kulit Lumpia Merk Fina', qtyOrder: '250 pcs', qtyArrived: '260 pcs', supplier: 'Tumpang Grosir', arrivalTime: '15.44', pic: 'Akmal', unitPrice: 1000, totalCost: 260000 },
    ],
  },
  {
    id: 'ORD-2026-004',
    date: '2026-09-23',
    poDate: 'Rabu, 22 Sept 2026',
    mealSession: 'Siang',
    menuTitle: 'Gado-Gado Komplit, Lontong Daun, Telur Rebus, Tempe & Tahu Goreng, Sayur Rebus, Semangka Segar',
    menuDescription: 'Menu gado-gado komplit kaya serat & protein: Lontong daun, telur ayam rebus, tahu tempe goreng, rebusan kubis, wortel, labu siam, kacang panjang, selada, dan potongan buah semangka segar.',
    specialDietB3: 'Menu B3 (Balita & Bumil): Lontong Sayur Lembut, Telur Rebus Halus, Tahu Tempe Kukus Bacem, Semangka Manis Potong',
    targetPortions: 3030,
    totalBeneficiaries: 3030,
    status: 'COMPLETED',
    chefInCharge: 'Chef Joko Santoso & Tim Dapur SPPG Jeru Tumpang',
    notes: 'Kebutuhan lontong daun siap santap sebanyak 3.060 pcs (tiba 3.100 pcs) bekerja sama dengan UMKM lokal Tumpang.',
    createdAt: '2026-09-22T14:00:00Z',
    beneficiaryAllocations: DEFAULT_SCHOOL_BENEFICIARIES.map(s => ({
      ...s,
      portionCount: Math.round(s.portionCount * (3030 / 3044)),
    })),
    keyIngredients: [
      { itemName: 'Lontong Daun Siap Saji', category: 'Bahan Olahan', quantity: 3060, unit: 'Bks', unitPrice: 2000, totalCost: 6120000 },
      { itemName: 'Telur Ayam Ras Segar', category: 'Bahan Basah', quantity: 21, unit: 'Krat (315 Kg)', unitPrice: 420000, totalCost: 8820000 },
      { itemName: 'Tahu & Tempe Kedelai', category: 'Bahan Basah', quantity: 587, unit: 'Pcs/Layah', unitPrice: 4000, totalCost: 2348000 },
      { itemName: 'Sayuran Rebus (Kubis, Wortel, Labu, Kacang Pjg)', category: 'Bahan Basah', quantity: 145, unit: 'Kg', unitPrice: 10000, totalCost: 1450000 },
      { itemName: 'Buah Semangka Merah Segar', category: 'Bahan Basah', quantity: 353, unit: 'Kg', unitPrice: 8500, totalCost: 3000500 },
      { itemName: 'Minyak Goreng & Bumbu Petis Asam', category: 'Bahan Kering', quantity: 6, unit: 'Dus/Kg', unitPrice: 200000, totalCost: 1200000 },
    ],
    poArrivalItems: [
      { category: 'Protein', itemName: 'Telur Ayam', qtyOrder: '21 krat', qtyArrived: '21 krat', supplier: 'Ayam Segar Tulus Besar', arrivalTime: '08.15', pic: 'Akmal', unitPrice: 420000, totalCost: 8820000 },
      { category: 'Protein', itemName: 'Tempe', qtyOrder: '77 layah', qtyArrived: '77 layah', supplier: 'Pak Slamet Tempe', arrivalTime: '15.30', pic: 'Akmal', unitPrice: 15000, totalCost: 1155000 },
      { category: 'Protein', itemName: 'Tahu Putih', qtyOrder: '510 pcs', qtyArrived: '510 pcs', supplier: 'Tahu Rio', arrivalTime: '15.20', pic: 'Akmal', unitPrice: 2500, totalCost: 1275000 },
      { category: 'Sembako', itemName: 'Minyak Goreng 2L per krtn 6pcs', qtyOrder: '5 karton', qtyArrived: '5 karton', supplier: 'Tumpang Grosir', arrivalTime: '15.10', pic: 'Akmal', unitPrice: 216000, totalCost: 1080000 },
      { category: 'Sembako', itemName: 'Royco Kaldu', qtyOrder: '1 karton', qtyArrived: '1 karton', supplier: 'Tumpang Grosir', arrivalTime: '15.10', pic: 'Akmal', unitPrice: 240000, totalCost: 240000 },
      { category: 'Sembako', itemName: 'Santan 1L per krtn 12pcs', qtyOrder: '1 karton', qtyArrived: '1 karton', supplier: 'Tumpang Grosir', arrivalTime: '15.10', pic: 'Akmal', unitPrice: 320000, totalCost: 320000 },
      { category: 'Sembako', itemName: 'Galon Cleo', qtyOrder: '10 pcs', qtyArrived: '10 pcs', supplier: 'Tumpang Grosir', arrivalTime: '15.10', pic: 'Akmal', unitPrice: 18000, totalCost: 180000 },
      { category: 'Bahan Olahan', itemName: 'Lontong', qtyOrder: '3060 pcs', qtyArrived: '1200+1350+550 = 3100 pcs', supplier: 'UMKM Berkah Lontong', arrivalTime: '06.00', pic: 'Akmal', unitPrice: 2000, totalCost: 6200000 },
      { category: 'Sayur', itemName: 'Kubis', qtyOrder: '40 kg', qtyArrived: '40 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 8000, totalCost: 320000 },
      { category: 'Sayur', itemName: 'Wortel', qtyOrder: '35 kg', qtyArrived: '35 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 12000, totalCost: 420000 },
      { category: 'Sayur', itemName: 'Labu Siam', qtyOrder: '35 kg', qtyArrived: '35 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 7000, totalCost: 245000 },
      { category: 'Sayur', itemName: 'Kacang Panjang', qtyOrder: '35 kg', qtyArrived: '45 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 9000, totalCost: 405000 },
      { category: 'Sayur', itemName: 'Selada', qtyOrder: '15 kg', qtyArrived: '15 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 15000, totalCost: 225000 },
      { category: 'Bumbu', itemName: 'Cabe Merah', qtyOrder: '3 kg', qtyArrived: '3 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 35000, totalCost: 105000 },
      { category: 'Bumbu', itemName: 'Petis Udang Super 1kg', qtyOrder: '2 kg', qtyArrived: '2 kg', supplier: 'Tumpang Grosir', arrivalTime: '15.10', pic: 'Akmal', unitPrice: 45000, totalCost: 90000 },
      { category: 'Bumbu', itemName: 'Asam Jawa 1/4kg', qtyOrder: '1/4 kg', qtyArrived: '1/4 kg', supplier: 'Tumpang Grosir', arrivalTime: '15.10', pic: 'Akmal', unitPrice: 8000, totalCost: 8000 },
      { category: 'Sayur', itemName: 'Kentang', qtyOrder: '3 kg', qtyArrived: '5 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 16000, totalCost: 80000 },
      { category: 'Bumbu', itemName: 'Bawang Merah', qtyOrder: '6 kg', qtyArrived: '6 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 34000, totalCost: 204000 },
      { category: 'Buah', itemName: 'Semangka', qtyOrder: '87 pc', qtyArrived: '353 kg', supplier: 'Mas Widi', arrivalTime: '16.40', pic: 'Akmal', unitPrice: 8500, totalCost: 3000500 },
    ],
  },
  {
    id: 'ORD-2026-005',
    date: '2026-09-24',
    poDate: 'Kamis, 23 Sept 2026',
    mealSession: 'Siang',
    menuTitle: 'Nasi Putih, Ayam Woku Kemangi, Tempe Goreng, Buncis & Jagung Manis, Buah Kelengkeng Manis',
    menuDescription: 'Menu lengkap beraroma rempah: Ayam ungkep woku bumbu rempah kemangi, tempe goreng renyah, tumis buncis jagung manis gurih, dan kelengkeng manis segar.',
    specialDietB3: 'Menu B3 (Balita & Bumil): Honey Garlic Chicken, Tempe Goreng, Buncis & Jagung, Curry Sauce Wortel Kentang, Tahu Goreng, Martabak Tahu, Kelengkeng',
    targetPortions: 3008,
    totalBeneficiaries: 3008,
    status: 'DISTRIBUTED',
    chefInCharge: 'Chef Joko Santoso & Tim Dapur SPPG Jeru Tumpang',
    notes: 'Total 3.008 penerima manfaat terdistribusi penuh. Penerimaan bahan tiba bertahap oleh PIC Akmal.',
    createdAt: '2026-09-23T10:00:00Z',
    beneficiaryAllocations: DEFAULT_SCHOOL_BENEFICIARIES.map(s => ({
      ...s,
      portionCount: Math.round(s.portionCount * (3008 / 3044)),
    })),
    keyIngredients: [
      { itemName: 'Beras Mentari 25kg', category: 'Bahan Kering', quantity: 7, unit: 'Sak (175 Kg)', unitPrice: 362500, totalCost: 2537500 },
      { itemName: 'Ayam Potong 10 pc', category: 'Bahan Basah', quantity: 310, unit: 'Kg', unitPrice: 38000, totalCost: 11780000 },
      { itemName: 'Tempe Segar', category: 'Bahan Basah', quantity: 78, unit: 'Layah', unitPrice: 15000, totalCost: 1170000 },
      { itemName: 'Buncis & Jagung Manis', category: 'Bahan Basah', quantity: 70, unit: 'Kg', unitPrice: 11000, totalCost: 770000 },
      { itemName: 'Buah Kelengkeng', category: 'Bahan Basah', quantity: 146, unit: 'Kg (12 Krat)', unitPrice: 28000, totalCost: 4099200 },
      { itemName: 'Minyak Goreng Tropical 2L', category: 'Bahan Kering', quantity: 5, unit: 'Karton (60 L)', unitPrice: 216000, totalCost: 1080000 },
      { itemName: 'Daun Kemangi, Tomat, Cabai & Bawang', category: 'Bahan Basah', quantity: 58, unit: 'Kg', unitPrice: 25000, totalCost: 1450000 },
    ],
    poArrivalItems: [
      { category: 'Protein', itemName: 'Ayam Potong 10 pc', qtyOrder: '310 kg', qtyArrived: '310 kg', supplier: 'Ayam Segar Fajar', arrivalTime: '12.05', pic: 'Akmal', unitPrice: 38000, totalCost: 11780000 },
      { category: 'Protein', itemName: 'Tempe', qtyOrder: '78 layah', qtyArrived: '78 layah', supplier: 'Pak Slamet Tempe', arrivalTime: '15.30', pic: 'Akmal', unitPrice: 15000, totalCost: 1170000 },
      { category: 'Sembako', itemName: 'Beras Mentari 25kg', qtyOrder: '7 sak', qtyArrived: '7 sak', supplier: 'Tumpang Grosir', arrivalTime: '13.40', pic: 'Akmal', unitPrice: 362500, totalCost: 2537500 },
      { category: 'Sembako', itemName: 'Minyak Goreng 2L per krtn 6pcs', qtyOrder: '5 ktn', qtyArrived: '5 ktn', supplier: 'Tumpang Grosir', arrivalTime: '13.40', pic: 'Akmal', unitPrice: 216000, totalCost: 1080000 },
      { category: 'Sembako', itemName: 'Madu Botol Besar', qtyOrder: '1 pc', qtyArrived: '1 pc', supplier: 'Tumpang Grosir', arrivalTime: '13.40', pic: 'Akmal', unitPrice: 65000, totalCost: 65000 },
      { category: 'Bumbu', itemName: 'Daun Jeruk', qtyOrder: '1/2 kg', qtyArrived: '1/2 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 20000, totalCost: 10000 },
      { category: 'Bumbu', itemName: 'Daun Salam', qtyOrder: '1 ikat', qtyArrived: '1 ikat', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 5000, totalCost: 5000 },
      { category: 'Sayur', itemName: 'Sledri', qtyOrder: '1 kg', qtyArrived: '1 ikat / 900 gr', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 20000, totalCost: 18000 },
      { category: 'Sayur', itemName: 'Daun Bawang', qtyOrder: '5 kg', qtyArrived: '5 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 18000, totalCost: 90000 },
      { category: 'Sayur', itemName: 'Tomat Buah', qtyOrder: '10 kg', qtyArrived: '12 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 12000, totalCost: 144000 },
      { category: 'Bumbu', itemName: 'Cabe Rawit', qtyOrder: '2 kg', qtyArrived: '2 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 35000, totalCost: 70000 },
      { category: 'Bumbu', itemName: 'Cabe Merah', qtyOrder: '10 kg', qtyArrived: '10 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 35000, totalCost: 350000 },
      { category: 'Bumbu', itemName: 'Bawang Putih', qtyOrder: '6 kg', qtyArrived: '6 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 36000, totalCost: 216000 },
      { category: 'Bumbu', itemName: 'Bawang Merah', qtyOrder: '10 kg', qtyArrived: '10 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 34000, totalCost: 340000 },
      { category: 'Bumbu', itemName: 'Kemangi Ikat Besar', qtyOrder: '1 kg', qtyArrived: '3 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 15000, totalCost: 45000 },
      { category: 'Bumbu', itemName: 'Sereh', qtyOrder: '3 ikat', qtyArrived: '3 ikat', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 5000, totalCost: 15000 },
      { category: 'Sayur', itemName: 'Labu Siam', qtyOrder: '2 kg', qtyArrived: '2 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 7000, totalCost: 14000 },
      { category: 'Sayur', itemName: 'Jagung Manis', qtyOrder: '50 buah', qtyArrived: '20,2 kg (+- 60 pcs)', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 10000, totalCost: 202000 },
      { category: 'Sayur', itemName: 'Buncis', qtyOrder: '50 kg', qtyArrived: '30,25+19,95 = 50,05 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 12000, totalCost: 600600 },
      { category: 'Sayur', itemName: 'Wortel', qtyOrder: '50 kg', qtyArrived: '49,70 kg', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 12000, totalCost: 596400 },
      { category: 'Buah', itemName: 'Kelengkeng', qtyOrder: '12 krat', qtyArrived: '12 krat (146,4 kg)', supplier: 'Mas Widi', arrivalTime: '15.45', pic: 'Akmal', unitPrice: 28000, totalCost: 4099200 },
    ],
  },
  {
    id: 'ORD-2026-006',
    date: '2026-09-27',
    poDate: 'Sabtu, 26 Sept 2026',
    mealSession: 'Siang',
    menuTitle: 'Nasi Putih Pulen, Ayam Goreng Lengkuas Rempah, Tempe Mendoan Gurih, Sayur Sop Segar, Buah Melon Manis',
    menuDescription: 'Menu pemenuhan gizi terpadu hari ini di SPPG Jeru Tumpang. Olahan ayam goreng bumbu lengkuas dengan tempe mendoan renyah gurih, kuah sup sayuran segar kaya vitamin, dan melon manis.',
    specialDietB3: 'Menu B3 (Balita & Bumil): Ayam Suwir Lengkuas Halus, Tempe Bacem Kukus, Sup Sayur Labu Wortel Cincang, Buah Melon Kupas',
    targetPortions: 3044,
    totalBeneficiaries: 3044,
    status: 'COOKING',
    chefInCharge: 'Chef Joko Santoso & Tim Dapur SPPG Jeru Tumpang',
    notes: 'Pelaksanaan operasional masak hari ini. 3.044 porsi dalam proses pengolahan dan pemorsian oleh tim dapur SPPG Jeru Tumpang.',
    createdAt: '2026-09-26T14:00:00Z',
    beneficiaryAllocations: DEFAULT_SCHOOL_BENEFICIARIES,
    keyIngredients: [
      { itemName: 'Beras Mentari 25kg', category: 'Bahan Kering', quantity: 7, unit: 'Sak (175 Kg)', unitPrice: 362500, totalCost: 2537500 },
      { itemName: 'Ayam Potong Segar', category: 'Bahan Basah', quantity: 264, unit: 'Kg', unitPrice: 38000, totalCost: 10032000 },
      { itemName: 'Tempe Daun Mendoan', category: 'Bahan Basah', quantity: 80, unit: 'Layah', unitPrice: 15000, totalCost: 1200000 },
      { itemName: 'Sayur Sop Campur (Wortel, Kubis, Buncis)', category: 'Bahan Basah', quantity: 80, unit: 'Kg', unitPrice: 12000, totalCost: 960000 },
      { itemName: 'Buah Melon Manis', category: 'Bahan Basah', quantity: 210, unit: 'Kg', unitPrice: 10000, totalCost: 2100000 },
      { itemName: 'Minyak Tropical 2L', category: 'Bahan Kering', quantity: 8, unit: 'Dus', unitPrice: 216000, totalCost: 1728000 },
      { itemName: 'Bumbu Dapur, Lengkuas, Bawang & Rempah', category: 'Bahan Basah', quantity: 35, unit: 'Kg', unitPrice: 28000, totalCost: 980000 },
    ],
    poArrivalItems: [
      { category: 'Protein', itemName: 'Ayam Potong Segar', qtyOrder: '264 kg', qtyArrived: '264 kg', supplier: 'Ayam Segar Fajar', arrivalTime: '08.15', pic: 'Akmal', unitPrice: 38000, totalCost: 10032000 },
      { category: 'Protein', itemName: 'Tempe Daun', qtyOrder: '80 layah', qtyArrived: '80 layah', supplier: 'Pak Slamet Tempe', arrivalTime: '08.45', pic: 'Akmal', unitPrice: 15000, totalCost: 1200000 },
      { category: 'Sembako', itemName: 'Beras Mentari 25kg', qtyOrder: '7 sak', qtyArrived: '7 sak', supplier: 'Tumpang Grosir', arrivalTime: '13.30', pic: 'Akmal', unitPrice: 362500, totalCost: 2537500 },
      { category: 'Sembako', itemName: 'Minyak Tropical 2L', qtyOrder: '8 dus', qtyArrived: '8 dus', supplier: 'Tumpang Grosir', arrivalTime: '13.30', pic: 'Akmal', unitPrice: 216000, totalCost: 1728000 },
      { category: 'Sayur & Buah', itemName: 'Wortel Segar Super', qtyOrder: '40 kg', qtyArrived: '40 kg', supplier: 'Sayur Segar Malang', arrivalTime: '07.30', pic: 'Akmal', unitPrice: 12000, totalCost: 480000 },
      { category: 'Sayur & Buah', itemName: 'Kubis Segar', qtyOrder: '40 kg', qtyArrived: '40 kg', supplier: 'Sayur Segar Malang', arrivalTime: '07.30', pic: 'Akmal', unitPrice: 8000, totalCost: 320000 },
      { category: 'Sayur & Buah', itemName: 'Buah Melon Manis', qtyOrder: '210 kg', qtyArrived: '210 kg', supplier: 'Buah Segar Nusantara', arrivalTime: '09.30', pic: 'Akmal', unitPrice: 10000, totalCost: 2100000 },
      { category: 'Bumbu', itemName: 'Lengkuas Segar', qtyOrder: '10 kg', qtyArrived: '10 kg', supplier: 'Toko Bumbu Berkah', arrivalTime: '08.00', pic: 'Akmal', unitPrice: 20000, totalCost: 200000 },
      { category: 'Bumbu', itemName: 'Bawang Merah & Putih', qtyOrder: '20 kg', qtyArrived: '20 kg', supplier: 'Toko Bumbu Berkah', arrivalTime: '08.00', pic: 'Akmal', unitPrice: 35000, totalCost: 700000 },
    ],
  },
];

export const REAL_EMPLOYEES: Employee[] = [
  {
    id: 'EMP-001',
    nik: '3507195408850001',
    nip: 'SPPG-JT-001',
    name: 'Rizky Iman Ramdhan, S.Pd',
    gender: 'L',
    phone: '0812-3344-5501',
    department: 'Manajemen & Administrasi',
    position: 'Kepala SPPG (Pimpinan Satuan Pelayanan)',
    employmentType: 'Tetap',
    shift: 'Full Day (05:00 - 17:00)',
    joinDate: '2026-01-02',
    status: 'AKTIF',
    address: 'Jl. Raya Tumpang No. 45, Kec. Tumpang, Kab. Malang',
    emergencyContact: '0812-9988-1122 (Keluarga)',
    notes: 'Penanggung jawab operasional penuh SPPG Jeru Tumpang',
  },
  {
    id: 'EMP-002',
    nik: '3507191206920002',
    nip: 'SPPG-JT-002',
    name: 'Andi Pratama, S.Gz',
    gender: 'L',
    phone: '0813-4455-6602',
    department: 'Gizi & Mutu',
    position: 'Asisten Lapangan & Ahli Gizi',
    employmentType: 'Tetap',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-01-10',
    status: 'AKTIF',
    address: 'Desa Jeru RT 03/RW 02, Tumpang',
    emergencyContact: '0813-8877-2233 (Orang Tua)',
    notes: 'Perhitungan Angka Kecukupan Gizi (AKG) & verifikasi menu siswa',
  },
  {
    id: 'EMP-003',
    nik: '3507194809950003',
    nip: 'SPPG-JT-003',
    name: 'Nurul Aini, A.Md.Gz',
    gender: 'P',
    phone: '0812-5566-7703',
    department: 'Gizi & Mutu',
    position: 'QC Pangan & Menu Diet Khusus B3',
    employmentType: 'Kontrak',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-01',
    status: 'AKTIF',
    address: 'Dusun Glanggang, Pakisaji, Malang',
    emergencyContact: '0857-1122-3344 (Ibu)',
    notes: 'Pengawasan higienitas sanitasi dan porsi balita 3T',
  },
  {
    id: 'EMP-004',
    nik: '3507191503880004',
    nip: 'SPPG-JT-004',
    name: 'Akmal',
    gender: 'L',
    phone: '0811-6677-8804',
    department: 'Gudang & Logistik',
    position: 'Kepala Gudang & Penerimaan Barang',
    employmentType: 'Tetap',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-01-05',
    status: 'AKTIF',
    address: 'Jl. Melati No. 12, Tumpang',
    emergencyContact: '0811-2233-4455 (Istri - Rini)',
    notes: 'Pemeriksaan timbangan PO & kartu stok gudang sembako',
  },
  {
    id: 'EMP-005',
    nik: '3507192207900005',
    nip: 'SPPG-JT-005',
    name: 'Slamet Riyadi',
    gender: 'L',
    phone: '0856-7788-9905',
    department: 'Gudang & Logistik',
    position: 'Staf Gudang & Penimbangan Masuk',
    employmentType: 'Kontrak',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-15',
    status: 'AKTIF',
    address: 'Desa Tulusbesar, Tumpang',
    emergencyContact: '0856-4433-2211 (Kakak)',
    notes: 'Penataan chiller basah dan gudang bumbu kering',
  },
  {
    id: 'EMP-006',
    nik: '3507191001800006',
    nip: 'SPPG-JT-006',
    name: 'Chef Joko Santoso',
    gender: 'L',
    phone: '0812-7890-1206',
    department: 'Dapur & Masak',
    position: 'Head Chef / Kepala Olahan Dapur',
    employmentType: 'Tetap',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-01-02',
    status: 'AKTIF',
    address: 'Jl. Candi Jago No. 8, Tumpang',
    emergencyContact: '0812-1100-9988 (Istri)',
    notes: 'Kepala dapur masak kapasitas 3.000 porsi per hari',
  },
  {
    id: 'EMP-007',
    nik: '3507191804870007',
    nip: 'SPPG-JT-007',
    name: 'Rahmat Hidayat',
    gender: 'L',
    phone: '0813-8901-2307',
    department: 'Dapur & Masak',
    position: 'Sous Chef / Juru Masak Utama',
    employmentType: 'Tetap',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-01-15',
    status: 'AKTIF',
    address: 'Desa Pulungdowo, Tumpang',
    emergencyContact: '0813-7766-5544 (Istri)',
    notes: 'Spesialis pengolahan lauk hewani & tumisan nusantara',
  },
  {
    id: 'EMP-008',
    nik: '3507192509910008',
    nip: 'SPPG-JT-008',
    name: 'Agus Setiawan',
    gender: 'L',
    phone: '0857-9012-3408',
    department: 'Dapur & Masak',
    position: 'Juru Masak Lauk Protein',
    employmentType: 'Kontrak',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-01',
    status: 'AKTIF',
    address: 'Desa Benjor, Tumpang',
    emergencyContact: '0857-8899-0011 (Ayah)',
    notes: 'Penanggung jawab penggorengan dan marinasi ayam/ikan',
  },
  {
    id: 'EMP-009',
    nik: '3507195205890009',
    nip: 'SPPG-JT-009',
    name: 'Sri Wahyuni',
    gender: 'P',
    phone: '0812-0123-4509',
    department: 'Dapur & Masak',
    position: 'Juru Masak Sayur & Kuah',
    employmentType: 'Kontrak',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-01-20',
    status: 'AKTIF',
    address: 'Desa Jeru RW 04, Tumpang',
    emergencyContact: '0812-3322-1100 (Suami)',
    notes: 'Pemasakan sup bening, sayur lodeh, dan oseng tempe',
  },
  {
    id: 'EMP-010',
    nik: '3507196008860010',
    nip: 'SPPG-JT-010',
    name: 'Sumiati',
    gender: 'P',
    phone: '0813-1234-5610',
    department: 'Dapur & Masak',
    position: 'Juru Masak Nasi & Karbohidrat',
    employmentType: 'Tetap',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-01-10',
    status: 'AKTIF',
    address: 'Desa Jeru RT 01/RW 01, Tumpang',
    emergencyContact: '0813-9988-7766 (Suami)',
    notes: 'Operasional 4 unit rice cooker gas otomatis 100 liter',
  },
  {
    id: 'EMP-011',
    nik: '3507194411930011',
    nip: 'SPPG-JT-011',
    name: 'Dewi Lestari',
    gender: 'P',
    phone: '0856-2345-6711',
    department: 'Dapur & Masak',
    position: 'Tim Preparasi & Potong Sayur',
    employmentType: 'Relawan / Mitra Harian',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-10',
    status: 'AKTIF',
    address: 'Desa Bokor, Tumpang',
    emergencyContact: '0856-1122-8877 (Ibu)',
    notes: 'Kupasan buncis, wortel, jagung pipil, dan labu siam',
  },
  {
    id: 'EMP-012',
    nik: '3507196602920012',
    nip: 'SPPG-JT-012',
    name: 'Siti Maimunah',
    gender: 'P',
    phone: '0812-3456-7812',
    department: 'Dapur & Masak',
    position: 'Tim Preparasi Daging & Bumbu Halus',
    employmentType: 'Relawan / Mitra Harian',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-10',
    status: 'AKTIF',
    address: 'Desa Kidal, Tumpang',
    emergencyContact: '0812-4455-6677 (Suami)',
    notes: 'Pemotongan fillet ayam dan peracikan rempah tradisional',
  },
  {
    id: 'EMP-013',
    nik: '3507191404940013',
    nip: 'SPPG-JT-013',
    name: 'Tri Wahyudi',
    gender: 'L',
    phone: '0813-4567-8913',
    department: 'Dapur & Masak',
    position: 'Tim Pemorsian & Packing Ombreng',
    employmentType: 'Kontrak',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-15',
    status: 'AKTIF',
    address: 'Desa Jeru RW 05, Tumpang',
    emergencyContact: '0813-3344-5566 (Kakak)',
    notes: 'Penimbangan porsi presisi dan susunan tray per sekolah',
  },
  {
    id: 'EMP-014',
    nik: '3507195907950014',
    nip: 'SPPG-JT-014',
    name: 'Rina Marlina',
    gender: 'P',
    phone: '0857-5678-9014',
    department: 'Dapur & Masak',
    position: 'Tim Pemorsian & Sealing Wadah',
    employmentType: 'Relawan / Mitra Harian',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-15',
    status: 'AKTIF',
    address: 'Desa Kambingan, Tumpang',
    emergencyContact: '0857-7788-9900 (Orang Tua)',
    notes: 'Quality control kebersihan wadah dan penutupan rapat',
  },
  {
    id: 'EMP-015',
    nik: '3507191112830015',
    nip: 'SPPG-JT-015',
    name: 'Bambang Supriyanto',
    gender: 'L',
    phone: '0812-6789-0115',
    department: 'Distribusi & Transport',
    position: 'Koordinator Driver Pengantaran Sekolah',
    employmentType: 'Tetap',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-01-08',
    status: 'AKTIF',
    address: 'Jl. Ki Ageng Gribig, Kedungkandang, Malang',
    emergencyContact: '0812-8899-1122 (Istri)',
    notes: 'Armada mobil box higienis rute SDN 1 Jeru & SMPN 1 Tumpang',
  },
  {
    id: 'EMP-016',
    nik: '3507192003920016',
    nip: 'SPPG-JT-016',
    name: 'Eko Prasetyo',
    gender: 'L',
    phone: '0813-7890-1216',
    department: 'Distribusi & Transport',
    position: 'Driver Distribusi Rute 02',
    employmentType: 'Kontrak',
    shift: 'Pagi (05:00 - 13:00)',
    joinDate: '2026-02-01',
    status: 'AKTIF',
    address: 'Desa Wringinsongo, Tumpang',
    emergencyContact: '0813-5566-7788 (Adik)',
    notes: 'Pengiriman rute Madrasah Ibtidaiyah & Posyandu B3',
  },
  {
    id: 'EMP-017',
    nik: '3507190505820017',
    nip: 'SPPG-JT-017',
    name: 'Suparno',
    gender: 'L',
    phone: '0856-8901-2317',
    department: 'Sanitasi & Kebersihan',
    position: 'Koordinator Sanitasi & Sterilisasi Alat',
    employmentType: 'Tetap',
    shift: 'Siang (10:00 - 18:00)',
    joinDate: '2026-01-12',
    status: 'AKTIF',
    address: 'Desa Jeru RW 02, Tumpang',
    emergencyContact: '0856-2233-4455 (Istri)',
    notes: 'Sterilisasi kompartemen nampan stainless steel dengan air panas 80C',
  },
  {
    id: 'EMP-018',
    nik: '3507191608930018',
    nip: 'SPPG-JT-018',
    name: 'Wawan Kurniawan',
    gender: 'L',
    phone: '0812-9012-3418',
    department: 'Sanitasi & Kebersihan',
    position: 'Petugas Pengelolaan Limbah & Residu Dapur',
    employmentType: 'Kontrak',
    shift: 'Siang (10:00 - 18:00)',
    joinDate: '2026-02-01',
    status: 'AKTIF',
    address: 'Desa Malangsuko, Tumpang',
    emergencyContact: '0812-6677-8899 (Ibu)',
    notes: 'Penimbangan sisa piring (plate waste) & serah terima pakan maggot',
  },
];

export const REAL_ATTENDANCE_LOGS: EmployeeAttendance[] = [
  // Presensi Hari Ini: 2026-09-23
  {
    id: 'ATT-20260923-001',
    date: '2026-09-23',
    employeeId: 'EMP-001',
    employeeName: 'Rizky Iman Ramdhan, S.Pd',
    department: 'Manajemen & Administrasi',
    position: 'Kepala SPPG',
    shift: 'Full Day (05:00 - 17:00)',
    checkInTime: '04:50',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Monitoring briefing pagi seluruh tim dapur',
    recordedBy: 'Rizky Iman Ramdhan, S.Pd',
    verified: true,
    createdAt: '2026-09-23T04:50:00Z',
  },
  {
    id: 'ATT-20260923-002',
    date: '2026-09-23',
    employeeId: 'EMP-002',
    employeeName: 'Andi Pratama, S.Gz',
    department: 'Gizi & Mutu',
    position: 'Asisten Lapangan & Ahli Gizi',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:55',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Uji organoleptik menu sayur sup & daging ayam fillet',
    recordedBy: 'Andi Pratama',
    verified: true,
    createdAt: '2026-09-23T04:55:00Z',
  },
  {
    id: 'ATT-20260923-003',
    date: '2026-09-23',
    employeeId: 'EMP-003',
    employeeName: 'Nurul Aini, A.Md.Gz',
    department: 'Gizi & Mutu',
    position: 'QC Pangan & Menu Diet Khusus B3',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '05:00',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Pemeriksaan suhu ruang saji & tekstur makanan balita',
    recordedBy: 'Andi Pratama',
    verified: true,
    createdAt: '2026-09-23T05:00:00Z',
  },
  {
    id: 'ATT-20260923-004',
    date: '2026-09-23',
    employeeId: 'EMP-004',
    employeeName: 'Akmal',
    department: 'Gudang & Logistik',
    position: 'Kepala Gudang & Penerimaan Barang',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:45',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Penerimaan beras mentari 7 sak dan minyak goreng',
    recordedBy: 'Akmal',
    verified: true,
    createdAt: '2026-09-23T04:45:00Z',
  },
  {
    id: 'ATT-20260923-005',
    date: '2026-09-23',
    employeeId: 'EMP-005',
    employeeName: 'Slamet Riyadi',
    department: 'Gudang & Logistik',
    position: 'Staf Gudang & Penimbangan Masuk',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:58',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Penimbangan ayam potong segar 260 Kg supplier Fajar',
    recordedBy: 'Akmal',
    verified: true,
    createdAt: '2026-09-23T04:58:00Z',
  },
  {
    id: 'ATT-20260923-006',
    date: '2026-09-23',
    employeeId: 'EMP-006',
    employeeName: 'Chef Joko Santoso',
    department: 'Dapur & Masak',
    position: 'Head Chef / Kepala Olahan Dapur',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:40',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Instruksi resep ayam fillet dan pengujian kuah sup',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T04:40:00Z',
  },
  {
    id: 'ATT-20260923-007',
    date: '2026-09-23',
    employeeId: 'EMP-007',
    employeeName: 'Rahmat Hidayat',
    department: 'Dapur & Masak',
    position: 'Sous Chef / Juru Masak Utama',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:52',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Memasak lauk hewani 3.000 porsi',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T04:52:00Z',
  },
  {
    id: 'ATT-20260923-008',
    date: '2026-09-23',
    employeeId: 'EMP-008',
    employeeName: 'Agus Setiawan',
    department: 'Dapur & Masak',
    position: 'Juru Masak Lauk Protein',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '05:15',
    checkOutTime: '',
    status: 'TERLAMBAT',
    lateMinutes: 15,
    notes: 'Kendala ban motor bocor di jalan raya Tumpang, sudah lapor Chef Joko',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T05:15:00Z',
  },
  {
    id: 'ATT-20260923-009',
    date: '2026-09-23',
    employeeId: 'EMP-009',
    employeeName: 'Sri Wahyuni',
    department: 'Dapur & Masak',
    position: 'Juru Masak Sayur & Kuah',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:58',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Merebus sup sayur buncis jagung manis',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T04:58:00Z',
  },
  {
    id: 'ATT-20260923-010',
    date: '2026-09-23',
    employeeId: 'EMP-010',
    employeeName: 'Sumiati',
    department: 'Dapur & Masak',
    position: 'Juru Masak Nasi & Karbohidrat',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:45',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Memasak beras mentari pulen 7 sak',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T04:45:00Z',
  },
  {
    id: 'ATT-20260923-011',
    date: '2026-09-23',
    employeeId: 'EMP-011',
    employeeName: 'Dewi Lestari',
    department: 'Dapur & Masak',
    position: 'Tim Preparasi & Potong Sayur',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '05:00',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Kupasan buncis & wortel segar 115 Kg',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T05:00:00Z',
  },
  {
    id: 'ATT-20260923-012',
    date: '2026-09-23',
    employeeId: 'EMP-012',
    employeeName: 'Siti Maimunah',
    department: 'Dapur & Masak',
    position: 'Tim Preparasi Daging & Bumbu Halus',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '',
    checkOutTime: '',
    status: 'SAKIT',
    notes: 'Flu dan demam tinggi, ada surat keterangan dokter Puskesmas Tumpang',
    recordedBy: 'Andi Pratama',
    verified: true,
    createdAt: '2026-09-23T06:00:00Z',
  },
  {
    id: 'ATT-20260923-013',
    date: '2026-09-23',
    employeeId: 'EMP-013',
    employeeName: 'Tri Wahyudi',
    department: 'Dapur & Masak',
    position: 'Tim Pemorsian & Packing Ombreng',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '05:05',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Packing 14 sekolah sasaran',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T05:05:00Z',
  },
  {
    id: 'ATT-20260923-014',
    date: '2026-09-23',
    employeeId: 'EMP-014',
    employeeName: 'Rina Marlina',
    department: 'Dapur & Masak',
    position: 'Tim Pemorsian & Sealing Wadah',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '05:02',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Penyegelan wadah higienis',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-23T05:02:00Z',
  },
  {
    id: 'ATT-20260923-015',
    date: '2026-09-23',
    employeeId: 'EMP-015',
    employeeName: 'Bambang Supriyanto',
    department: 'Distribusi & Transport',
    position: 'Koordinator Driver Pengantaran Sekolah',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '05:00',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Pengiriman rute 01 SDN Jeru & SMPN Tumpang',
    recordedBy: 'Akmal',
    verified: true,
    createdAt: '2026-09-23T05:00:00Z',
  },
  {
    id: 'ATT-20260923-016',
    date: '2026-09-23',
    employeeId: 'EMP-016',
    employeeName: 'Eko Prasetyo',
    department: 'Distribusi & Transport',
    position: 'Driver Distribusi Rute 02',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:55',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Pengiriman rute 02 MI & Posyandu B3',
    recordedBy: 'Akmal',
    verified: true,
    createdAt: '2026-09-23T04:55:00Z',
  },
  {
    id: 'ATT-20260923-017',
    date: '2026-09-23',
    employeeId: 'EMP-017',
    employeeName: 'Suparno',
    department: 'Sanitasi & Kebersihan',
    position: 'Koordinator Sanitasi & Sterilisasi Alat',
    shift: 'Siang (10:00 - 18:00)',
    checkInTime: '09:50',
    checkOutTime: '',
    status: 'HADIR',
    notes: 'Pencucian nampan makanan gelombang 1',
    recordedBy: 'Suparno',
    verified: true,
    createdAt: '2026-09-23T09:50:00Z',
  },
  {
    id: 'ATT-20260923-018',
    date: '2026-09-23',
    employeeId: 'EMP-018',
    employeeName: 'Wawan Kurniawan',
    department: 'Sanitasi & Kebersihan',
    position: 'Petugas Pengelolaan Limbah & Residu Dapur',
    shift: 'Siang (10:00 - 18:00)',
    checkInTime: '',
    checkOutTime: '',
    status: 'IZIN',
    notes: 'Izin urusan administrasi keluarga mendadak (sudah disetujui Ka SPPG)',
    recordedBy: 'Rizky Iman Ramdhan, S.Pd',
    verified: true,
    createdAt: '2026-09-23T08:00:00Z',
  },

  // Presensi Kemarin: 2026-09-22
  {
    id: 'ATT-20260922-001',
    date: '2026-09-22',
    employeeId: 'EMP-001',
    employeeName: 'Rizky Iman Ramdhan, S.Pd',
    department: 'Manajemen & Administrasi',
    position: 'Kepala SPPG',
    shift: 'Full Day (05:00 - 17:00)',
    checkInTime: '04:55',
    checkOutTime: '17:15',
    status: 'HADIR',
    notes: 'Rapat koordinasi bersama BGN & dinas kesehatan',
    recordedBy: 'Rizky Iman Ramdhan, S.Pd',
    verified: true,
    createdAt: '2026-09-22T04:55:00Z',
  },
  {
    id: 'ATT-20260922-002',
    date: '2026-09-22',
    employeeId: 'EMP-002',
    employeeName: 'Andi Pratama, S.Gz',
    department: 'Gizi & Mutu',
    position: 'Asisten Lapangan & Ahli Gizi',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:50',
    checkOutTime: '13:30',
    status: 'HADIR',
    notes: 'Audit gizi lengkap 3.030 porsi',
    recordedBy: 'Andi Pratama',
    verified: true,
    createdAt: '2026-09-22T04:50:00Z',
  },
  {
    id: 'ATT-20260922-006',
    date: '2026-09-22',
    employeeId: 'EMP-006',
    employeeName: 'Chef Joko Santoso',
    department: 'Dapur & Masak',
    position: 'Head Chef / Kepala Olahan Dapur',
    shift: 'Pagi (05:00 - 13:00)',
    checkInTime: '04:35',
    checkOutTime: '13:45',
    status: 'HADIR',
    notes: 'Pengawasan produksi nasi uduk & ayam goreng rempah',
    recordedBy: 'Chef Joko Santoso',
    verified: true,
    createdAt: '2026-09-22T04:35:00Z',
  },
];

