// Auto-generated real seed data from rekap_stok_gudang_sppg.xlsx
import { NonFoodExpense, WasteLog, ItemMaster } from '../types/warehouse';

export const REAL_NONFOOD_EXPENSES: NonFoodExpense[] = [
  {
    "id": "PRL-EXP-001",
    "date": "20 sept 2026",
    "itemName": "kresek merah",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "19.55",
    "volunteer": "roni",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "roni",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 19.55 oleh roni",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-002",
    "date": "20 sept 2026",
    "itemName": "trashbag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "20.30",
    "volunteer": "puspitasari",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "puspitasari",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.30 oleh puspitasari",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-003",
    "date": "20 sept 2026",
    "itemName": "obat mylanta",
    "quantity": "1 kaplet",
    "unit": "Pack",
    "time": "21.37",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 21.37 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-004",
    "date": "20 sept 2026",
    "itemName": "handsaplast",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "23.00",
    "volunteer": "nafis",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nafis",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.00 oleh nafis",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-005",
    "date": "20 sept 2026",
    "itemName": "handsaplast",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "23.17",
    "volunteer": "usli",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "usli",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.17 oleh usli",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-006",
    "date": "20 sept 2026",
    "itemName": "tissue",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "23.17",
    "volunteer": "b sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "b sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.17 oleh b sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-007",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 bendel",
    "unit": "Pack",
    "time": "23.17",
    "volunteer": "b sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "b sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 23.17 oleh b sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-008",
    "date": "21 sept 2026",
    "itemName": "trash bag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "01.36",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 01.36 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-009",
    "date": "21 sept 2026",
    "itemName": "masker 1 pack hijab",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "03.03",
    "volunteer": "lutvya",
    "pic": "riski",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutvya",
    "recordedBy": "riski",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.03 oleh lutvya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-010",
    "date": "21 sept 2026",
    "itemName": "plastik buah",
    "quantity": "7 pack",
    "unit": "Pack",
    "time": "03.03",
    "volunteer": "lutvya",
    "pic": "riski",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutvya",
    "recordedBy": "riski",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.03 oleh lutvya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-011",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "03.03",
    "volunteer": "lutvya",
    "pic": "riski",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutvya",
    "recordedBy": "riski",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.03 oleh lutvya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-012",
    "date": "21 sept 2026",
    "itemName": "trashbag 60x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "03.21",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 03.21 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-013",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "05.57",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 05.57 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-014",
    "date": "21 sept 2026",
    "itemName": "kresek merah",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "08.19",
    "volunteer": "nabila",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 08.19 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-015",
    "date": "21 sept 2026",
    "itemName": "rinso softergent",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "10.02",
    "volunteer": "nabila",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 10.02 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-016",
    "date": "21 sept 2026",
    "itemName": "trashbag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "12.18",
    "volunteer": "dudin",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "dudin",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 12.18 oleh dudin",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-017",
    "date": "21 sept 2026",
    "itemName": "sunlight",
    "quantity": "1 jurigen",
    "unit": "Pack",
    "time": "12.20",
    "volunteer": "zenli",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "zenli",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 12.20 oleh zenli",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-018",
    "date": "21 sept 2026",
    "itemName": "wipol oxyklin",
    "quantity": "1 jurigen",
    "unit": "Pack",
    "time": "13.40",
    "volunteer": "nabila",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 13.40 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-019",
    "date": "21 sept 2026",
    "itemName": "sarung tangan",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "18.15",
    "volunteer": "anggita",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "anggita",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 18.15 oleh anggita",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-020",
    "date": "21 sept 2026",
    "itemName": "sarung tangan plastik",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "18.15",
    "volunteer": "angita",
    "pic": "teguh",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "angita",
    "recordedBy": "teguh",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 18.15 oleh angita",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-021",
    "date": "21 sept 2026",
    "itemName": "tissue",
    "quantity": "1pack",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "nafis",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nafis",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh nafis",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-022",
    "date": "21 sept 2026",
    "itemName": "salonpas koyo",
    "quantity": "1 biji",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-023",
    "date": "21 sept 2026",
    "itemName": "minyak kayu putih",
    "quantity": "1 botol",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "bu nur",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu nur",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh bu nur",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-024",
    "date": "21 sept 2026",
    "itemName": "handsaplast koyo",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "20.55",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.55 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-025",
    "date": "22 sept 2026",
    "itemName": "trashbag 60x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "00.29",
    "volunteer": "saiful",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saiful",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 00.29 oleh saiful",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-026",
    "date": "22 sept 2026",
    "itemName": "handsaplast",
    "quantity": "2 biji",
    "unit": "Pack",
    "time": "04.38",
    "volunteer": "lutfiya",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "lutfiya",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 04.38 oleh lutfiya",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-027",
    "date": "22 sept 2026",
    "itemName": "soklin softergent kecil",
    "quantity": "1 pcs",
    "unit": "Pack",
    "time": "08.23",
    "volunteer": "andri",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "andri",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 08.23 oleh andri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-028",
    "date": "22 sept 2026",
    "itemName": "sarung tangan karet biru",
    "quantity": "1 pcs",
    "unit": "Pack",
    "time": "09.24",
    "volunteer": "nabila",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "nabila",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 09.24 oleh nabila",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-029",
    "date": "22 sept 2026",
    "itemName": "trash bag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "12.20",
    "volunteer": "mansur",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "mansur",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 12.20 oleh mansur",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-030",
    "date": "22 sept 2026",
    "itemName": "sunlight jurigen 5l",
    "quantity": "1 pcs",
    "unit": "Pack",
    "time": "13.48",
    "volunteer": "dudin",
    "pic": "akmal",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "dudin",
    "recordedBy": "akmal",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 13.48 oleh dudin",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-031",
    "date": "22 sept 2026",
    "itemName": "sarung tangan karet biru",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "19.43",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 19.43 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-032",
    "date": "22 sept 2026",
    "itemName": "trash bag 80x10",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "20.00",
    "volunteer": "saipul",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "saipul",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 20.00 oleh saipul",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "PRL-EXP-033",
    "date": "22 sept 2026",
    "itemName": "tissue dapur besar",
    "quantity": "1 pack",
    "unit": "Pack",
    "time": "19.43",
    "volunteer": "bu sri",
    "pic": "ade",
    "category": "Peralatan & Kebersihan",
    "department": "Dapur Pengolahan Utama",
    "recipient": "bu sri",
    "recordedBy": "ade",
    "unitPrice": 0,
    "totalCost": 0,
    "notes": "Jam ambil 19.43 oleh bu sri",
    "createdAt": "2026-09-21T00:00:00Z"
  }
];

export const REAL_WASTE_LOGS: WasteLog[] = [
  {
    "id": "WST-001",
    "day": "jumat",
    "date": "2026-09-18",
    "wasteCategory": "karbohidrat",
    "itemName": "Limbah karbohidrat",
    "quantity": 64.16,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-002",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "sayur",
    "itemName": "Limbah sayur",
    "quantity": 48.12,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-003",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "protein hewani",
    "itemName": "Limbah protein hewani",
    "quantity": 16.4,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-004",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "protein nabati",
    "itemName": "Limbah protein nabati",
    "quantity": 24.6,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-005",
    "day": "Jumat",
    "date": "2026-09-18",
    "wasteCategory": "buah",
    "itemName": "Limbah buah",
    "quantity": 8.02,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-006",
    "day": "senin",
    "date": "2026-09-21",
    "wasteCategory": "karbohidrat",
    "itemName": "Limbah karbohidrat",
    "quantity": 62.92,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-007",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "sayur",
    "itemName": "Limbah sayur",
    "quantity": 47.19,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-008",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "protein hewani",
    "itemName": "Limbah protein hewani",
    "quantity": 15.73,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-009",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "protein nabati",
    "itemName": "Limbah protein nabati",
    "quantity": 23.6,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  },
  {
    "id": "WST-010",
    "day": "Senin",
    "date": "2026-09-21",
    "wasteCategory": "buah",
    "itemName": "Limbah buah",
    "quantity": 7.86,
    "unit": "Kg",
    "sourceArea": "SPPG Jeru Tumpang",
    "reason": "Sisa preparasi & porsi olahan dapur",
    "disposalMethod": "Pakan Ternak & Kompos Organik",
    "recordedBy": "Tim Dapur Jeru",
    "createdAt": "2026-09-21T00:00:00Z"
  }
];

export const REAL_EQUIPMENT_ITEMS: ItemMaster[] = [
  {
    "id": "PRL-001",
    "name": "natura desinfectant food grade 5l",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 2,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "tanggal so gudang per 21 september 2026",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-002",
    "name": "sunlight cairan pencuci piring 5l",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 4,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-003",
    "name": "oixs cleaner 1l",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-004",
    "name": "be clean tissue serbaguna",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 3,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-005",
    "name": "spons cuci hijau",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 10,
    "reorderPoint": 20,
    "currentStock": 37,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-006",
    "name": "sabut cuci stainless",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 22,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-007",
    "name": "plastik kresek besar merah 50pc",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 8,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-008",
    "name": "lap besar",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 4,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-009",
    "name": "lap microfiber",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 67,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-010",
    "name": "lap kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 7,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-011",
    "name": "kanebo kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 6,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-012",
    "name": "plastik 1/4kg joyoboyo 100 lembar",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 28,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-013",
    "name": "sarung tangan plastik kaka 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 21,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-014",
    "name": "optima trashbag 80x100",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 7,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-015",
    "name": "optima trashbag 60x100",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-016",
    "name": "rajawali trashbag 30x40",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 5,
    "reorderPoint": 10,
    "currentStock": 1.5,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-017",
    "name": "onemed masker biru 3 play 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 6,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-018",
    "name": "onemed masker biru 3 play hijab 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-019",
    "name": "neo health masker biru 3 play 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 9,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-020",
    "name": "baymed masker hijau 3 play hijau 50 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 2,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-021",
    "name": "altamed nurse cap penutup kepala 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 5,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-022",
    "name": "sabun cuci tangan",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-023",
    "name": "gayung kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-024",
    "name": "cikrak kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-025",
    "name": "petromax plastik kecil 12x24 100 lembar",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-026",
    "name": "lancar kresek kecil bening",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 2.5,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-027",
    "name": "kresek klin warna warni kecil",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 2,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-028",
    "name": "ctik plastik 7x10 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 81,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-029",
    "name": "ctik plastik 6x10 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 13,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-030",
    "name": "klip plastik 25x16 100 pcs",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pack",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 1,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-031",
    "name": "tempat saus 20 ml",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 2,
    "reorderPoint": 4,
    "currentStock": 20,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  },
  {
    "id": "PRL-032",
    "name": "plastik packaging ag box uk sedang",
    "itemType": "OPERATIONAL_CONSUMABLE",
    "category": "Peralatan",
    "subcategory": "Peralatan & Sanitasi",
    "baseUnit": "pcs",
    "minimumStock": 100,
    "reorderPoint": 200,
    "currentStock": 2000,
    "location": "gudang peralatan",
    "expiryTrackingEnabled": false,
    "isActive": true,
    "notes": "Data SO Gudang SPPG",
    "lastMovementDate": "2026-09-21"
  }
];
